# Defines the design of the whole page
# Possible values: [FIN, OvGU]
design: OvGU

mode: preregistration #preregistration/registration/closed

menu:
  legals: true
  courses: true
  news: true
  programs: true
  downloads: true
  my_group: true

administration:
  send_new_user_registered_notification: true

mail:
  from: "no-reply@anywhere.com"
  smtp:
    server_address: "mail.anywhere.com"
    port: 587
    user_name: "user"
    password: "myOwnSecret"
  #All Mails are getting bypassed to this adress while in devolpment Mode
  development_bypass_target: "nobody@example.com"

vorkurs_test:
  categorized_question: true
  max_questions_per_test: 10
  randomized_questioning: true
  max_answers_per_question: 4

debug:
  show_question_ids: true